apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollup-demo
  labels:
    app: rollup-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollup-demo
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: rollup-demo
    spec:
      containers:
      - name: rollup-demo
        image: rollup-demo:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4200
        readinessProbe:
          httpGet:
            path: /
            port: 4200
          periodSeconds: 3

---

kind: Service
apiVersion: v1
metadata:
  name: rollup-demo
spec:
  selector:
    app: rollup-demo
  ports:
  - port: 4200
    targetPort: 4200
  type: NodePort
